language: go

sudo: false

env:
  global:
    - GO111MODULE=on

go:
  - "1.12"
  - "1.11"
  - "1.10"

cache:
  directories:
    - $GOPATH/pkg/mod

script:
  - if [ $TRAVIS_GO_VERSION == "1.12" ]; then
      make setup_ci;
      go mod verify;
      go mod vendor && GO111MODULE=off PATH=$TRAVIS_BUILD_DIR/bin:$PATH make lint;
      rm -rf vendor;
    fi
  - make build
  - make test
  - "[ $TRAVIS_GO_VERSION != '1.12' ] || make upload_coverage"
